# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-10 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='Comments',
            field=models.TextField(max_length=300, verbose_name='\u062a\u0648\u0636\u06cc\u062d\u0627\u062a'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='summary',
            field=models.TextField(default='\u062e\u0644\u0627\u0635\u0647 \u0641\u0639\u0627\u0644\u06cc\u062a', max_length=300, verbose_name='\u062e\u0644\u0627\u0635\u0647 \u0641\u0639\u0627\u0644\u06cc\u062a'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='title',
            field=models.CharField(default='\u0639\u0646\u0648\u0627\u0646 \u0641\u0639\u0627\u0644\u06cc\u062a', max_length=100, verbose_name='\u0639\u0646\u0648\u0627\u0646'),
        ),
    ]
