# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-10 16:42
from __future__ import unicode_literals

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolApp', '0002_auto_20160810_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='date',
            field=django_jalali.db.models.jDateField(verbose_name='\u062a\u0627\u0631\u06cc\u062e'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='date',
            field=django_jalali.db.models.jDateField(verbose_name='\u062a\u0627\u0631\u06cc\u062e'),
        ),
        migrations.AlterField(
            model_name='consultationschedule',
            name='date',
            field=django_jalali.db.models.jDateField(verbose_name='\u062a\u0627\u0631\u06cc\u062e'),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=django_jalali.db.models.jDateField(verbose_name='\u062a\u0627\u0631\u06cc\u062e'),
        ),
    ]
