# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-10 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolApp', '0003_auto_20160810_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(verbose_name='\u062a\u0627\u0631\u06cc\u062e'),
        ),
    ]
