# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-10 18:06
from __future__ import unicode_literals

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolApp', '0004_auto_20160810_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=django_jalali.db.models.jDateField(verbose_name='\u062a\u0627\u0631\u06cc\u062e'),
        ),
    ]
